version: '3.8'

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./fe:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./be:/app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_policy_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: